DROP TABLE IF EXISTS agent;
DROP TABLE IF EXISTS call_data;
DROP TABLE IF EXISTS audits;
DROP TABLE IF EXISTS corrections;
DROP TABLE IF EXISTS datedim;

CREATE TABLE IF NOT EXISTS datedim (
    DATE DATE PRIMARY KEY
    , WEEKDAY TEXT NOT NULL
    , YEARWEEK TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS agent (
    AGENTID INTEGER PRIMARY KEY
    , AGENTTITLE TEXT NOT NULL
    , AGENTLEADERID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS call_data (
    CALLID INTEGER PRIMARY KEY
    , AGENTID INTEGER NOT NULL
    , CALLSTARTDATE DATE NOT NULL
    , CONVERTED BOOL NOT NULL
    , CALLENDREASON TEXT NOT NULL
    , FOREIGN KEY(AGENTID) REFERENCES agent(AGENTID)
    , FOREIGN KEY(CALLSTARTDATE) REFERENCES datedim(DATE)
);

CREATE TABLE IF NOT EXISTS audits(
    AUDITID INTEGER PRIMARY KEY
    , CALLID INTEGER NOT NULL
    , CALLSTARTDATE DATE NOT NULL
    , CONVERTED BOOL NOT NULL
    , CALLENDREASON TEXT NOT NULL
    , AGENTTITLE TEXT NOT NULL
    , AGENTLEADERID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS corrections(
    CORRECTIONID INTEGER PRIMARY KEY
    , AUDITID INTEGER NOT NULL
    , CALLID INTEGER NOT NULL
    , CALLSTARTDATE DATE NOT NULL
    , CONVERTED BOOL NOT NULL
    , CALLENDREASON TEXT NOT NULL
    , AGENTTITLE TEXT NOT NULL
    , AGENTLEADERID INTEGER NOT NULL
    , FOREIGN KEY(AUDITID) REFERENCES audits(AUDITID)
);
