DROP TABLE IF EXISTS agent;
DROP TABLE IF EXISTS call_data;
DROP TABLE IF EXISTS audits;
DROP TABLE IF EXISTS corrections;
DROP TABLE IF EXISTS datedim;

CREATE TABLE IF NOT EXISTS datedim (
    DATE DATE PRIMARY KEY
    , WEEKDAY TEXT NOT NULL
    , YEARWEEK TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS agent (
    AGENTID INTEGER PRIMARY KEY
    , AGENTTITLE TEXT NOT NULL
    , AGENTLEADERID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS call_data (
    CALLID INTEGER PRIMARY KEY
    , AGENTID INTEGER NOT NULL
    , CALLSTARTDATE DATE NOT NULL
    , CONVERTED BOOL NOT NULL
    , CALLENDREASON TEXT NOT NULL
    , FOREIGN KEY(AGENTID) REFERENCES agent(AGENTID)
    , FOREIGN KEY(CALLSTARTDATE) REFERENCES datedim(DATE)
);

CREATE TABLE IF NOT EXISTS audits(
    , CALLID INTEGER PRIMARY KEY
    , INSERTEDDATETIME CURRENT_TIMESTAMP
    , CALLSTARTDATE DATE NOT NULL
    , CONVERTED BOOL NOT NULL
    , CALLENDREASON TEXT NOT NULL
    , AGENTID INTEGER NOT NULL
    , AGENTTITLE TEXT NOT NULL
    , AGENTLEADERID INTEGER NOT NULL
    , QA_INTRODUCTION TEXT
    , QA_OBJECTION TEXT
    , QA_SCRIPT TEXT
    , QA_VERIFICATION TEXT
    , QA_TONE TEXT
    , QA_DEADAIR TEXT
    , QA_NOTES TEXT
    , TL_INTRODUCTION TEXT
    , TL_OBJECTION TEXT
    , TL_SCRIPT TEXT
    , TL_VERIFICATION TEXT
    , TL_TONE TEXT
    , TL_DEADAIR TEXT
    , TL_NOTES TEXT
);

CREATE TABLE IF NOT EXISTS corrections(
    CORRECTIONID INTEGER PRIMARY KEY
    , CORRECTIONINSERTEDDATETIME CURRENT_TIMESTAMP
    , CALLID INTEGER NOT NULL
    , CALLSTARTDATE DATE NOT NULL
    , CONVERTED BOOL NOT NULL
    , CALLENDREASON TEXT NOT NULL
    , AGENTTITLE TEXT NOT NULL
    , AGENTID INTEGER NOT NULL
    , AGENTLEADERID INTEGER NOT NULL
    , QA_INTRODUCTION BOOL
    , QA_OBJECTION BOOL
    , QA_SCRIPT BOOL
    , QA_VERIFICATION BOOL
    , QA_TONE BOOL
    , QA_DEADAIR BOOL
    , QA_NOTES TEXT
    , TL_INTRODUCTION BOOL
    , TL_OBJECTION BOOL
    , TL_SCRIPT BOOL
    , TL_VERIFICATION BOOL
    , TL_TONE BOOL
    , TL_DEADAIR BOOL
    , TL_NOTES TEXT
    , FOREIGN KEY(CALLID) REFERENCES audits(CALLID)
);

CREATE TEMPORARY VIEW IF NOT EXISTS dashboard(
    WITH combined_forms AS (
        SELECT *
        FROM audits a
            WHERE a.callid NOT IN (
                SELECT DISTINCT CALLID
                FROM corrections c
            )

        UNION ALL

        SELECT CALLID
            , CALLSTARTDATE
            , CONVERTED
            , CALLENDREASON
            , AGENTTITLE
            , AGENTID
            , AGENTLEADERID
            , QA_INTRODUCTION
            , QA_OBJECTION
            , QA_SCRIPT
            , QA_VERIFICATION
            , QA_TONE
            , QA_DEADAIR
            , QA_NOTES
            , TL_INTRODUCTION
            , TL_OBJECTION
            , TL_SCRIPT
            , TL_VERIFICATION
            , TL_TONE
            , TL_DEADAIR
            , TL_NOTES
        FROM (
            SELECT *
                , ROW_NUMBER() OVER(
                    PARTITION BY callid
                    ORDER BY CORRECTIONINSERTEDDATETIME DESC
                ) last_submission
            FROM corrections
        ) c
        WHERE c.last_submission = 1
    )
)
