CREATE TABLE IF NOT EXISTS call_data (
    CALLID INTEGER PRIMARY KEY
    , ROSTERID INTEGER NOT NULL
    , CALLSTARTDATETIME DATETIME NOT NULL
    , CALLENDATETIME DATETIME NOT NULL
    , TRANSFERSTARTDATETIME DATETIME
    , TRANSFERCOMPLETEDATETIME DATETIME
    , CALLENDREASON TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS agent (
    AGENTID INTEGER PRIMARY KEY
    , AGENTTITLE TEXT NOT NULL
    , AGENTLEADERID INTEGER NOT NULL
);

-- CREATE TABLE IF NOT EXISTS audits(
--     AUDITID INTEGER PRIMARY KEY
-- );
